### ISSUE TITLE
Profil banner is gone

### ISSUE THREAD

**Issue by UsikaDesu** [refact0r/system24#3]
Discord profile banner is gone while using this theme
(---------------------FIXED---------------------)
![image](https://github.com/refact0r/system24/assets/109031388/a1c0d970-2b1a-409f-b17c-10ddcba22969)

**Comment by UsikaDesu** [comment]
Profile banner bug is fixed

----------------------CLOSED----------------------

**Comment by refact0r** [comment]
fixed in [b8749b2](https://github.com/refact0r/system24/commit/b8749b272523c69a390dc0d2cc671e2e6c1ab7b5)
