### ISSUE TITLE
unthemed bits: popups and embed subtitles

### ISSUE THREAD

**Issue by stellophiliac** [refact0r/system24#32]
<img width="464" src="https://github.com/user-attachments/assets/e9a6889e-eedc-4529-a85c-0b3ce5fce8a7">

<img width="431" src="https://github.com/user-attachments/assets/4b004373-7bf4-48e0-b2dc-9455c3dd0485">

^ the channel name here is white, noticeable on light themes

**Comment by stellophiliac** [comment]
found a few more small things!

- spoilers seem to be unthemed
- settings tabs (eg. in profiles, the "user profile" and "server profiles" tabs) have a default blurple underline
- "1 new" etc. on forum channels are blurple
- some muted text things (eg. "enter your pronouns") are the default color
- the shadow in grid-view forums are also the default color

i'll see if any of these things i can try to fix sometime

**Comment by stellophiliac** [comment]
trying to fiddle around with this— side note, discord seem to have some weird overrides in light mode. kind of annoying and i'm not sure if there's a fix for that

**Comment by bbb651** [comment]
Some other examples of popups:
- Channel description
![image](https://github.com/user-attachments/assets/9e5c807a-6ffa-4e21-8afb-00ae63548238)
- Notifications settings
![image](https://github.com/user-attachments/assets/1d154cb7-4499-4c1b-aca4-36cc46da7ca1)
- Privacy settings
![image](https://github.com/user-attachments/assets/11d70f79-56bf-4de4-b58d-fb5afd9ae209)
- Invite to server (names devtooled out)
![image](https://github.com/user-attachments/assets/eb9d13d1-fb03-406a-bdca-c9be51e5493a)
![image](https://github.com/user-attachments/assets/47983535-c231-4aa1-a00a-f39e37a8c789)
- Add status
![image](https://github.com/user-attachments/assets/7a25a0ce-9c29-4368-8b18-b08b6d0fc020)
- Add friend nickname
![image](https://github.com/user-attachments/assets/9c574d9e-12da-488a-8d35-ebb5a77a6e29)
- Create/join server
![image](https://github.com/user-attachments/assets/35ff0ade-73ac-4475-9234-feb10485554d)
![image](https://github.com/user-attachments/assets/15f0df0f-18ac-48ca-b63d-e418898f8cc5)
![image](https://github.com/user-attachments/assets/9ed36f39-6187-49e5-aabe-34c81b99e992)
![image](https://github.com/user-attachments/assets/5055e1c6-3f49-42b5-9dee-04a4795d702f)
- Invite screen
![image](https://github.com/user-attachments/assets/c9aeb145-b577-4620-9988-15dbea6cd65c)
- Gift
![image](https://github.com/user-attachments/assets/b1f16c84-4c07-429a-b3ac-ba56f4e11c1e)
- App launcher
![image](https://github.com/user-attachments/assets/ad34c128-1446-43ac-9208-a8dffed86496)
- Add app
![image](https://github.com/user-attachments/assets/f1c82bba-2372-4d64-ab62-4f26bbf8b69b)
- Remove friend
![image](https://github.com/user-attachments/assets/efc125bc-4df3-4ca4-a496-826cf295af7f)
- Failed friend request
![image](https://github.com/user-attachments/assets/99760750-2903-4b5b-b455-ef0004986434)
- Block user
![image](https://github.com/user-attachments/assets/e6d272b1-eefa-4f33-8bc9-e643aa7cc40b)
- Relax with Wumpus (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Alt</kbd> + <kbd>W</kbd>)
![image](https://github.com/user-attachments/assets/36de6a55-b32e-46c7-9f11-7317bd4112ef)
- 100 server limit (probably)

Some other small things:
- Add status bubble in own profile
![image](https://github.com/user-attachments/assets/abc9791e-1a5b-41f0-85b9-aa4ac2ce3096)
- Pfp hover shadow should be sqaure
![image](https://github.com/user-attachments/assets/63b924fd-e28c-48bb-8343-d9661ecc29df)
- Mic test button text cuts off
![image](https://github.com/user-attachments/assets/45be5086-aacf-4911-9c1e-d35bfcf4f425)
- Download desktop app popup uses wrong accent color
![image](https://github.com/user-attachments/assets/aecc1f5a-3167-492c-8695-4986aabaf10a)
- App directory category text cuts off
![image](https://github.com/user-attachments/assets/ceaf2900-ba46-4bcf-b595-3d3cf453b188)

**Comment by stellophiliac** [comment]
more issues from the server:

- "input" title shows up when making forums
- "open in browser" isn't very visible
