### ISSUE TITLE
Theme broken on new design

### ISSUE THREAD

**Issue by eveee00** [refact0r/system24#34]
Hello, the theme appears to be broken on the redesign of the discord app. I assume it will be fixed when the redesign officially comes out, but I also wanted to ask here about it.

<img width="1680" alt="Screenshot 2024-09-25 at 22 51 33" src="https://github.com/user-attachments/assets/7d358635-3e41-4c81-acaa-72ce889a69a6">

**Comment by refact0r** [comment]
i'd probably just rewrite the theme if redesign actually comes out. the redesign is in a pretty bad state at the moment so im not even sure if they are releasing it. until then i will not work on making the theme work for the redesign.
