### ISSUE TITLE
some small color fixes

### ISSUE THREAD

**Issue by 909oce** [refact0r/system24#38]
I wasn't entirely sure where to put this in the source file to submit as a pull request, and probably isn't the most optimal way, but heres a few small coloring fixes I added to my theme.css. It fixes some placeholder text, some overlays like the add friends to conversation, and reaction buttons.

```
:root {
  --primary-700: var(--bg-0);
  --primary-600: var(--bg-1);
  --primary-330: var(--txt-2);
  --primary-400: var(--acc-2);
  --brand-360: var(--acc-1);
  --primary-630: var(--bg-1);
  --brand-15a: var(--bg-1);
  --brand-200: var(--txt-2);
}

::placeholder {
  color: var(--txt-3)!important;
}

```

**Comment by 909oce** [comment]
This fixes most of #32

**Comment by stellophiliac** [comment]
i'm working on a pr (https://github.com/refact0r/system24/pull/33) with a lot of fixes for the issue i opened, i'll add your changes to mine if that's ok? :D

**Comment by 909oce** [comment]
> i'm working on a pr (#33) with a lot of fixes for the issue i opened, i'll add your changes to mine if that's ok? :D

yeah please do. theres also --primary-130 which fixes the weird bright white highlight on mic mute button in calls.

**Comment by 909oce** [comment]
@stellophiliac ive left the things i mentioned above out of my PR as to not step on yours.
