### ISSUE TITLE
indicators variables not changing the actual indicator colors

### ISSUE THREAD

**Issue by RootOperator** [refact0r/system24#4]
the --online-dot, --dnd-dot, --idle-dot variables don't seem to change the colors of the indicators in discord

changing the colors of these variables in the QuickCSS in vencord
![image](https://github.com/refact0r/system24/assets/20143055/6f6849c8-6d42-4592-a1b9-92301b5e3d5d)

results in nothing happening

![image](https://github.com/refact0r/system24/assets/20143055/accd7052-0891-45bb-aabc-25ba5d5e3668)

**Comment by refact0r** [comment]
oops
