### ISSUE TITLE
Feature request: Ascii font as channel headers

### ISSUE THREAD

**Issue by cj2tech** [refact0r/system24#53]
This worked for me

```
@import url("https://fonts.cdnfonts.com/css/asciid");
/* Header Ascii Text */
[class*="heading-xxl\/semibold_"] {
    font-family: "asciid";
    font-size: 40px;
    color: var(txt-2);
}

[class*="defaultMarginh1"],
[class*="defaultMarginh2"] {
    font-family: "asciid";
    font-size: 30px;
    color: var(txt-2);
}

[class*="heading-xxl\/extrabold_"] {
    font-family: "asciid";
    font-size: 40px;
    color: var(txt-2);
}

[class*="emptyChannelIconComponent_"] {
    display: none;
}
```

**Comment by refact0r** [comment]
im not gonna change the base font

**Comment by cj2tech** [comment]
Not changing the base font just changing the font of the headers to look more inline with the theme,
![image](https://github.com/user-attachments/assets/5e293ed1-63fc-442a-9c52-a9b8c8f033ca)

**Comment by refact0r** [comment]
ohh i misunderstood. will take a closer look.

**Comment by cj2tech** [comment]
No worries I explained it pretty badly. Prob would of help if I started with a pic

**Comment by refact0r** [comment]
yeah i think this only makes sense to use for the title at the start of channels. in other places there just isn't enough space for it to look good.

**Comment by refact0r** [comment]
thanks for the idea
