### ISSUE TITLE
Activity Now section cutting off screen

### ISSUE THREAD

**Issue by rxbb21** [refact0r/system24#54]
Activity Now section keeps cutting off the screen, it randomly may fix itself for 5 mins then break again for long periods, and unable to read what people r doing or view what channel they r in ect. image below is how my discord looks, its hard to tell due to hiding usernames but the activity now section is only showing a small portion and very annoying.
![Untitled](https://github.com/user-attachments/assets/77c7ac35-010f-4fd4-b8dd-80eb773d68b7)

**Comment by SuppliedOrange** [comment]
+1

This occurs due to long statuses I believe. Statuses need to be truncated.

![image](https://github.com/user-attachments/assets/681ca4fc-4aa9-461a-a09b-fc08c2e9e18d)

**Comment by rxbb21** [comment]
> 1 solution is to set `max-width: 50rem` for `peopleColumn`? This scales effectively for everyone?
> 
> 
> 
> ![image (32)](https://github.com/user-attachments/assets/4f76acbd-3862-4586-9dda-007ff42d9c6b)
> 
> 

how do i do that?

**Comment by rxbb21** [comment]
will you be able to explain clearly for a nooby at this as i have no clue where to edit or change stuff.

**Comment by SuppliedOrange** [comment]
@rxbb21 sure, simply change your `system24.theme.css` file's line like this:
```css
@import url('https://refact0r.github.io/system24/src/main.css');
```
to
```css
@import url('https://raw.githubusercontent.com/SuppliedOrange/system24/refs/heads/main/src/main.css');
```
This re-directs it to my modified version of the repository (see https://github.com/refact0r/system24/pull/57) and it changes what I mentioned earlier. You'd wanna change this back once the PR gets merged.
