### ISSUE TITLE
window buttons disappear

### ISSUE THREAD

**Issue by blindmodz** [refact0r/system24#8]
As the tittle says, window buttons disappear when you double click on inbox.
Tried to replicate with midnight skin but doesn't happen so I assume it's related to the skin.
![wxDyrayqTp](https://github.com/user-attachments/assets/dd0fe64c-dae7-486a-9f88-a1ec92bd7913)

**Comment by refact0r** [comment]
please check if this is fixed on your end

**Comment by blindmodz** [comment]
Yes :D
